# Site settings
title: Pierluisvona
email: hello@pierluisvona.it
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/plv_website/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
instagram_username: pierluisvona

# Build settings
markdown: kramdown
permalink: pretty



social:
  - title: behance
    url: https://www.behance.net/pierluisvona
  - title: instagram
    url: https://www.instagram.com/pierluisvona/
  - title: linkedin
    url: https://www.linkedin.com/in/pierluigi-vona-30415812b/
  - title: pinterest
    url: https://it.pinterest.com/pgvona/
  - title: twitter
    url: https://twitter.com/PierluisVona
