title:  "MontiLab"
tagline: "workshop di progettazione partecipata, website"
description:

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Storia del progetto', file: 'story.html'}
- {name: 'Tutor', file: 'tutor.html'}
- {name: 'Techlab.tl', file: 'contact.html'}

social:
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
#- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}
#- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
